import './js/fetchBooks';
import './js/modal';
import './js/auth-modal';
import './js/scroll-up';
import './js/darkTheme';
import './js/shopping-list/getShoppingList';
import './js/header';
import './js/support';
import './js/auth';
